project:
  type: website

website:
  title: "Problema de Clasificación"
  navbar:
    left:
      - href: index.qmd
        text: Introducción
      - href: preparacion.qmd
        text: Preparación de los datos
      - href: analisis.qmd
        text: Análisis exploratorio
      - href: modelado.qmd
        text: Modelado
      - href: evaluacion.qmd
        text: Evaluación
      - href: about.qmd
        text: Acerca De

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

